##############################
########## WINDOWS ###########
##############################

# See https://wiki.hypr.land/Configuring/Window-Rules/ for more

## Ignore maximize requests from all apps.
#windowrule {
#    name = suppress-maximize-events
#    match:class = .*
#
#    suppress_event = maximize
#}


# Waypaper
#windowrule = match:class waypaper, float true

# Waybar apps
#windowrule = float on, match:class ^(floating)$
#windowrule = size 900 500, match:class ^(floating)$
#windowrule = center on, match:class ^(floating)$

#windowrule {
#    name = compact-pavucontrol
#    match:class = org.pulseaudio.pavucontrol
#
#    float = true
#    size = 600 480 
#}

