## Sweet-Ambar-Blue Kitty Theme

# Cores fundamentais
background            #0b0b0d
foreground            #fcfcfc
selection_background  #fcfcfc
selection_foreground  #101013
url_color             #0072ff
cursor                #fcfcfc

# Transparência (Baseado no Opacity=0.85 e Blur=true do seu config)
background_opacity 0.85
dynamic_background_opacity yes

# Cores do Terminal (ANSI)

# Black
color0  #232627
color8  #7f8c8d

# Red
color1  #ed254e
color9  #ed254e

# Green
color2  #71f79f
color10 #71f79f

# Yellow
color3  #fadd00
color11 #fadd00

# Blue
color4  #0072ff
color12 #0072ff

# Magenta
color5  #d400dc
color13 #d400dc

# Cyan
color6  #00c1e4
color14 #00c1e4

# White
color7  #fcfcfc
color15 #ffffff
