# Import colors
include colors.conf

# Font
font_family JetBrains Mono Nerd Font
font_size 10

# Kitty specifics
disable_ligatures always
disable_ligaturs no
enable_audio_bell no
remember_window_size no
cursor_blink_interval 0

# Shell
shell fish

# Scroll
map page_up    scroll_page_up
map page_down    scroll_page_down

# Background and window
window_padding_width 8
scrollbar_handle_opacity 0
scrollbar_track_opacity 0
scrollbar_track_hover_opacity 0
confirm_os_window_close 0
background_opacity 0.85
dynamic_background_opacity yes

# Cursor
cursor_trail 1
cursor_shape block

# Mouse
url_style curly
open_url_with default
copy_on_select yes

# Remote control
allow_remote_control yes

# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
