# Max allowed gamma (optional)
max-gamma = 150

# Daytime profile (normal colors)
profile {
    time = 07:30       # Time time at which the profile should activate
    identity = true    # Ignore temperature value
    gamma = 1.0        # Brightness
}

# Evening profile
profile {
    time = 21:00
    temperature = 5500 # Screeen mask, lower means warmer (default = 6000)
}

# Night-time profile
profile {
    time = 22:30
    temperature = 5000
}
