# Hyprland config (SlowerTrick)

######################
### EXTERNAL FILES ###
######################
source = ./components/env.conf
source = ./components/monitors.conf
source = ./components/programs.conf
source = ./components/autostart.conf
source = ./components/colors.conf
source = ./components/permissions.conf
source = ./components/workspaces.conf
source = ./components/windows.conf
source = ./components/window_rules.conf
source = ./components/appearence.conf
source = ./components/input.conf
source = ./components/binds.conf
